kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
    - protocol: "TCP"
      port: 32401
      targetPort: 9094
  type: LoadBalancer
  loadBalancerIP: 35.234.10.79 #this is a FIXED IP WE RESERVE ON Google Cloud
  externalTrafficPolicy: "Local"
  # ports:
  # - protocol: TCP
  #   targetPort: 9094
  #   port: 32401
  #   nodePort: 32401
  # type: NodePort